filter:
    paths:
        - 'web/*'
        - 'executor/*'
    excluded_paths:
        - '*/migrations/*'
        - '*/static/*'
        - '*/submfiles/*'
checks:
    python:
        code_rating: true
        duplicate_code: true
