# Generated by Django 4.0.6 on 2022-07-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensubmit', '0036_alter_assignment_course_alter_course_lti_key_and_more'),
        ('opensubmit', '0036_auto_20190305_0911'),
    ]

    operations = [
    ]
